CREATE TABLE medications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    active_ingredient VARCHAR(120),
    presentation VARCHAR(80),
    notes VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE
);
