CREATE TABLE prescriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    medication_id BIGINT NOT NULL,
    dosage_amount NUMERIC(10, 2) NOT NULL,
    dosage_unit VARCHAR(30) NOT NULL,
    frequency VARCHAR(80) NOT NULL,
    scheduled_time TIME,
    start_date DATE NOT NULL,
    continuous_use BOOLEAN NOT NULL DEFAULT FALSE,
    stock_quantity NUMERIC(10, 2),
    minimum_stock_alert NUMERIC(10, 2),
    instructions VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_prescriptions_patient FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT fk_prescriptions_medication FOREIGN KEY (medication_id) REFERENCES medications (id)
);
